### ISSUE TITLE
get list of stocks

### ISSUE THREAD

**Issue by christophpickl** [christophpickl/payconiq#2]
# Tasks

- [x] implement `GET /api/stocks` endpoint; stocks got the following properties:
  - id (Number)
  - name (String)
  - currentPrice (Amount)
  - lastUpdate (Timestamp)
- [x] write integration tests
- [x] use an in-memory persistence layer

# Acceptance Criteria

- [x] endpoint returns list of default stocks
- [x] integration tests succeed on travis
