### ISSUE TITLE
get single stock item

### ISSUE THREAD

**Issue by christophpickl** [christophpickl/payconiq#3]
# Tasks

- [x] implement `GET /api/stocks/$stockId` endpoint
- [x] add custom exception handler for 404 not found
- [x] update persistence layer
- [x] write integration tests

# Acceptance Criteria

- [x] endpoint returns 200 on found and 404 on not found stock
- [ ] integration tests succeed on travis
