### ISSUE TITLE
update a stock item

### ISSUE THREAD

**Issue by christophpickl** [christophpickl/payconiq#4]
# Tasks

- [x] implement `PUT /api/stocks/$stockId` endpoint; updates the price of a single stock
- [x] update persistence layer
- [x] write integration tests

# Acceptance Criteria

- [x] endpoint returns 200 on found and 404 on not found stock
- [x] integration tests succeed on travis
